config/routes.rb
Rails.application.routes.draw do
  
  get 'links/new'

  get 'tools/new'

  
  root              'static_pages#home'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'

  get 'media'   =>  'static_pages#media'
  get 'tools'   =>  'static_pages#tools'

  get 'linktool' =>  'links#new'
  resources :links

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	# Basic Pages
	def home
	end

	def help
	end

	def about
	end

	def contact
	end

	# Extra Pages
	def media
	end
	
	def tools
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "The Warehouse"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb

<footer class="footer navbar-fixed-bottom">
	
	<small>The Warehouse 2015</small>

	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "The Warehouse", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li> <%= link_to "Home", root_path %> </li>
				<li> <%= link_to "Media", media_path %> </li>
				<li> <%= link_to "Tools", tools_path %> </li>
				<li> <%= link_to "Help", help_path %> </li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
	<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title (yield(:title)) %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<%= render 'layouts/shim'%>

</head>
<body>

	<%= render 'layouts/header'%>

	<% flash.each do |message_type, message| %>
	<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
	
	<div class="contatiner">
		<%= yield %>
	</div>

	<br><br>
	
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>

<center>
	<p>What do you want to know?</p>
</center>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

<center>
	<p>

		<h3>Administrator</h3>
		<b>Name:</b> Brian<br>
		<b>E-mail:</b> carlson.b99@gmail.com<br>

	</p>
</center>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<h2>Help will be coming shortly. Hang tight my dude.</h2> <br>
	<div>
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<p>
						
					</p>
				</div>
			</div>
		</div>
	</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Brian's Projects</h1>
	<h2>Welcome to the home page</h2>
</div>

	<div>
		<div class="container">
			<div class="col-md-6">
				<p>
					I hope to house a selection of project I have worked on, as well as some web based tools, in this site.
				</p>
			</div>
		</div>
	</div>

app/views/static_pages/media.html.erb
<% provide(:title, "Media") %>

<h1>Media</h1>

<div>
	<div class="container">

		<!-- Links to provided services -->
		<div class="row">
			<div class="col-md-12">
				<h3>Services</h3>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<h3><a href="http://media-server.homenet.org:32400/web">Plex</a></h3>
				<p>
					This is a streaming service for all of the Movies and Shows on The Warehouse. It provides easy access to all of the content, regardless of codec, from any device. It can be viewed through the web player with this link.
				</p>
			</div>


			<div class="col-md-6">
				<h3><a href="http://media-server.homenet.org:4040">Madsonic</a></h3>
				<p>
					This is a music streaming service for all of the Music on The Warehouse. It provides easy access the entire database of music on The Warehouse. It can be used through the link with the provided credentials.
				</p>
			</div>
		</div>

		<br><br>

		<!-- Database Controllers -->
		<div class="row">
			<div class="col-md-12">
				<h3>Databases</h3>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<h3><%= link_to "Movie Database", '#' %></h3>
				<p>
					This is a current database of all of the Movies on The Warehouse. This provides a tabular view of all of the Movies, allowing for easy browsing and searching. Some Movies can be viewed directly through the browser from the database. Others cannot and must be viewed through Plex or a program like <a href="http://www.videolan.org/vlc/index.html">VLC</a>.
				</p>
			</div>

			<div class="col-md-6">
				<h3><%= link_to "Show Database", '#' %></h3>
				<p>
					This is a current database of all of the Shows on The Warehouse. This provides a tabular view of all of the Shows, allowing for easy browsing and searching. Some episodes can be viewed directly through the browser from the database. Others cannot and must be viewed through Plex or a program like <a href="http://www.videolan.org/vlc/index.html">VLC</a>.
				</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<h3><%= link_to "Music Database", '#' %></h3>
				<p>
					This is a current database of all of the Music on The Warehouse. Music can be browsed, played and downloaded from here. It does not provide a library or player feature like Madsonic. This is simply a tabular view of the Music for simplified searching and downloading. 
				</p>
			</div>
		</div>



	</div>
</div>


app/views/static_pages/tools.html.erb
<% provide(:title, "Tools") %>

<h1>Tools</h1>
<p>
	<h2>Some useful tools ... maybe</h2> <br>

	<div>
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h3><%= link_to "Link Generator", linktool_path %></h3>
					<p>
						This tool converts a file path from the Media Drive, and returns an external share link to the file.
					</p>
				</div>
			</div>
		</div>
	</div>